### ISSUE TITLE
Flower Map not showing up/Pulling random image

### ISSUE THREAD

**Issue by AspieGamer13** [Draradech/FlowerMap#2]
Mod Version: 1.2.3
Mod Loader: Fabric
Game Version: 1.19.4

See attached image, but when I try to use Flower Map, I get a random image instead. This has been an issue for me for several versions (since I started trying to use it in 1.18.2), but I figure it's about time I mention it/seek help. I've had the thumbnails for other mods show up instead as well, but this time it looks to have grabbed the icon texture file from the appleskin mod.

![2023-04-27_16 51 30](https://user-images.githubusercontent.com/95000468/234989074-521c999e-5350-4fdf-970e-af09bf2fc147.png)

**Comment by LangKeWAVE** [comment]
are you downland api?

**Comment by Draradech** [comment]
I'm unable to reproduce this. Please try in 1.20. If you still have problems, attach your latest.log, in case there is something logged there.

**Comment by AspieGamer13** [comment]
Sorry for the delay. It took nearly a month for most of my other used mods to update as well. I wanted to give the test a normal use test just in case.

I tested in 1.20 and it seems to have self-corrected. I tried testing in older versions, but for some reason they won't load and I can't test.

**Comment by Draradech** [comment]
OK. Thanks for the info. If you have problems in the future, feel free to open a new issue.

**Comment by plutonium-239** [comment]
Hey, I am seeing this issue on 1.20.1 too
Here is a representation:
![image](https://github.com/Draradech/FlowerMap/assets/29684689/8393812f-978e-43c3-8ac6-02704e196796)

(customhud plugin overlapping)


UPDATE:
I restarted my game and it has shown the flower map. 
However, for biomes outside the flower forest, it shows the colors changing very quickly like a lot of static noise.

**Comment by Draradech** [comment]
The static noise is expected behaviour. The mod asks the game for a flower for that location and gets a different answer every frame for locations in which multiple flower types might grow.
